[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
celery = "^5.4.0"
flask = "^3.0.3"
flask-socketio = "^5.4.1"
gevent = "^24.10.2"
gevent-websocket = "^0.10.1"
redis = "^5.1.1"
